[package]
name = "png_image"
version = "0.1.0"
authors = ["XDA-7 <xaraxsaren@hotmail.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
